# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

MenuName.create(
    [
        {name: "ベンチプレス "},
        {name: "スミスマシン・ベンチプレス"},
        {name: "インクライン・ベンチプレス"},
        {name: "ダンベル・ベンチプレス "},
        {name: "ダンベル・フライ"},
        {name: "ケーブル・クロスオーバー"},
        {name: "懸垂(チンニング)"},
        {name: "ベントオーバーロウ"},
        {name: "ケーブル・プルオーバー"},
        {name: "デッドリフト"},
        {name: "トップサイド・デッドリフト"},
        {name: "ルーマニアン・デッドリフト"},
        {name: "スモウ・デッドリフト"},
        {name: "ペック・フライ"},
        {name: "ナロー・ベンチプレス"},
        {name: "インクライン・ダンベル・ベンチプレス"},
        {name: "インクライン・ダンベルフライ"},
        {name: "ワンハンド・ダンベル・ローイング"},
        {name: "ロー・プーリー・ロウ"},
        {name: "ラット・プルダウン"},
        {name: "レッグ・エクステンション"},
        {name: "レッグ・カール"},
        {name: "レッグ・プレス"},
        {name: "バーベル・カール"},
        {name: "ダンベル・カール"},
        {name: "オルタネイト・ダンベル・カール"},
        {name: "インクライン・ダンベル・カール"},
        {name: "プリーチャー・カール"},
        {name: "スパイダー・カール"},
        {name: "ケーブル・カール"},
        {name: "トライセプス・プレスダウン"},
        {name: "トライセプス・プッシュダウン"},
        {name: "トライセプス・エクステンション"},
        {name: "ケーブル・オーバーヘッドエクステンション"},
        {name: "サイドレイズ"},
        {name: "ワンハンド・サイドレイズ"},
        {name: "インクライン・サイドレイズ"},
        {name: "ケーブル・サイドレイズ"},
        {name: "ダンベル・ショルダープレス"},
        {name: "バーベル・ショルダープレス"},
        {name: "スミスマシン・ショルダープレス"},
        {name: "バーベル・バックプレス"},
        {name: "フロントレイズ"},
        {name: "インクライン・フロントレイズ"},
        {name: "リアレイズ"},
        {name: "インクライン・リアレイズ"},
        {name: "リアデルトフライ"},
        {name: "クランチ"},
        {name: "シットアップ"},
        {name: "レッグレイズ"},
        {name: "アブローラー（腹筋ローラー）"},
        {name: "ハンギング・レッグレイズ"},
        {name: "スクワット"},
        {name: "ハックスクワット"},
        {name: "レッグ・プレス"},
        {name: "レッグ・エクステンション"},
        {name: "レッグ・カール"},
        {name: "カーフ・レイズ"}
        ]
    )
